### ISSUE TITLE
[UI - My Wallet] On a smaller desktop screen, my wallet UI breaks

### ISSUE THREAD

**Issue by OneCodeMan** [MacAquafina/reframery-frontend#101]
# Summary
On a smaller desktop screen, my wallet UI breaks

# Environment
Platform: Desktop
OS: Mac
Browser: Safari

# Steps to Reproduce
1. Go to `http://localhost:3000/cart`
2. Make window smaller
3. Observe UI breaking

<img width="1220" alt="Bildschirmfoto 2021-03-03 um 20 16 37" src="https://user-images.githubusercontent.com/15069287/109895817-e7576800-7c5d-11eb-9960-d637dfa33c60.png">
<img width="899" alt="Bildschirmfoto 2021-03-03 um 20 16 55" src="https://user-images.githubusercontent.com/15069287/109895823-e9212b80-7c5d-11eb-9e59-3769d521f165.png">
<img width="912" alt="Bildschirmfoto 2021-03-03 um 20 16 59" src="https://user-images.githubusercontent.com/15069287/109895824-e9b9c200-7c5d-11eb-8623-6b9cd995ddf7.png">

**Comment by liangw27** [comment]
Solved
