### ISSUE TITLE
TypeError: Cannot read property 'currentCredit' of undefined

### ISSUE THREAD

**Issue by sophiajwchoi** [MacAquafina/reframery-frontend#110]
## Expected Behavior
- When the user navigates the cart page at http://localhost:3000/cart and clicks on WALLET on the left, it should open up the wallet page?

## Actual Behavior
- When the user navigates the cart page at http://localhost:3000/cart and clicks on WALLET on the left gives me an error

![image](https://user-images.githubusercontent.com/34407972/109914411-ec2c1400-7c7d-11eb-82e9-7d65ef99fdff.png)

## Steps to Reproduce the Problem

  1.   http://localhost:3000/cart 
  1.  Click on WALLET
 

## Specifications

  - Platform: Windows 10 64

**Comment by liangw27** [comment]
Duplicate issue with #29

**Comment by liangw27** [comment]
Duplicate issue with #29
