### ISSUE TITLE
TypeError: Cannot read property 'userImage' of null

### ISSUE THREAD

**Issue by sophiajwchoi** [MacAquafina/reframery-frontend#111]
## Expected Behavior
- On the shopping cart page, when I click Transactions on the left, transactions should show up.

## Actual Behavior

![image](https://user-images.githubusercontent.com/34407972/109914411-ec2c1400-7c7d-11eb-82e9-7d65ef99fdff.png)

## Steps to Reproduce the Problem

  1.   http://localhost:3000/cart 
  1.  Click on Transactions
 

## Specifications

  - Platform: Windows 10 64

**Comment by liangw27** [comment]
Same as #31
