### ISSUE TITLE
Uploading non-image file for image upload on create item page should return an error

### ISSUE THREAD

**Issue by sophiajwchoi** [MacAquafina/reframery-frontend#121]
# Expected Behavior
- When the user uploads a non-image file for an image of a product, it should return an error

## Actual Behavior
- No response

## Steps to Reproduce the Problem

  1. Navigate to http://localhost:3000/create-item
  1. Upload a text file for Image for Item
 
## Specifications

  - Platform: Chrome Windows 10

**Comment by LIUK44** [comment]
We haven't embedded a backend for uploading image files but we now are using an image hosting service to generate imageURL.
