### ISSUE TITLE
Uploading image on "create item" page doesn't work

### ISSUE THREAD

**Issue by Gregory-Kitching** [MacAquafina/reframery-frontend#124]
Uploading an image to the create item page shows no indication that an item has been uploaded.

Steps to reproduce:
1. Sign in
2. Go to "my item" -> "create item"
3. Fill out item information
4. Click "Image for item" button
5. Select an image file
6. Press "open"

![Screenshot from 2021-03-04 13-42-48](https://user-images.githubusercontent.com/79662360/110013753-069ed580-7cf0-11eb-9d0d-62295b4f18b8.png)
"Create item" page before and after attempting to upload an image

![Screenshot from 2021-03-04 13-43-36](https://user-images.githubusercontent.com/79662360/110013853-20401d00-7cf0-11eb-9c5d-344745c43cc8.png)
Clicking the "image for item" button causes this screen to pop up

**Comment by LIUK44** [comment]
It works now by uploading imageURL.
