### ISSUE TITLE
Phone number area code

### ISSUE THREAD

**Issue by Wesley-Guoxy** [MacAquafina/reframery-frontend#138]
## Description:
I am studying how the form works in the profile page. After I fail uploading profile image, I try to fill in my phone number. My phone number should start with “+86” but I find the input box automatically splits my phone number with only one number following “+”. It would be better if I can input my phone number like “+86 XXXX” with a whitespace after the right phone area code.

## Environment:
Windows10, NodeJS14.16.0,  Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	go to the profile page
2.	fill in the phone number box
 
![image](https://user-images.githubusercontent.com/42874340/110435349-dee3af00-80ed-11eb-8911-7771931bd498.png)
3. click on add
![image](https://user-images.githubusercontent.com/42874340/110435379-e99e4400-80ed-11eb-810e-6b99f359d0a1.png)

 

## Expected Result:
the input box of phone number split my phone number in a right way.

## Severity: 
LOW

**Comment by FangY2019** [comment]
For an invalid phone number, it will not split the number correctly by our current React phone number input component. 

![1](https://user-images.githubusercontent.com/54195303/111056204-3dd95900-844b-11eb-87f4-17e42b51149d.PNG)

![2](https://user-images.githubusercontent.com/54195303/111056209-4598fd80-844b-11eb-82d3-6036d81c4160.PNG)
