### ISSUE TITLE
Can't see my balance

### ISSUE THREAD

**Issue by Wesley-Guoxy** [MacAquafina/reframery-frontend#140]
## Description:
I am trying to glance at my balance and run into a 404 error. It seems that my account is not correctly registered.

## Environment:
Windows10, NodeJS14.16.0, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	visit balance page and you will see
 
![image](https://user-images.githubusercontent.com/42874340/110440447-9fb85c80-80f3-11eb-89e4-e93eaeb854d9.png)

## Expected Result:
show my balance normally without throwing any error messages

## Severity: 
HIGH

**Comment by liangw27** [comment]
Solved when I add the data of transactions in database.
