### ISSUE TITLE
No detailed information of items

### ISSUE THREAD

**Issue by Wesley-Guoxy** [MacAquafina/reframery-frontend#143]
## Description:
Since there are many appealing items in the Canada market place, why not buy some for myself? Holding the idea I visit the item page by clicking “Items” in the left sidebar. I can see many goods including products and services. Unexpected happens when I click on one of the items to find more detailed information that nothing shows up in the new page I open.
## Environment:
Windows10, NodeJS14.16.0, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	visit main page
2.	click on the “Items” hyperlink in the left sidebar
3.	choose one favorite item to click on
 
![image](https://user-images.githubusercontent.com/42874340/110444317-d55f4480-80f7-11eb-828e-790981f8f96d.png)

4.	nothing shows up in the item page
 
![image](https://user-images.githubusercontent.com/42874340/110444323-d6907180-80f7-11eb-8abc-73f344410905.png)

## Expected Result:
When I try to find the information of a certain item through main page, I can see page like below
 
![image](https://user-images.githubusercontent.com/42874340/110444326-d85a3500-80f7-11eb-826c-c3c00717cb68.png)

## Severity: 
HIGH

**Comment by LIUK44** [comment]
The Item Page was intended to display all items created by the current login user, not for detailed information.
