### ISSUE TITLE
Problem with administration management

### ISSUE THREAD

**Issue by Wesley-Guoxy** [MacAquafina/reframery-frontend#146]
## Description:
I try to login as a manager and find something interesting about the administrator management. It seems that I can change any user’s balance as I want. So I try to find a user existed in the user system and change his/her balance. But I can’t see the searching result of the management page.

## Environment:
Windows10, NodeJS14.16.0, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	login as a manager
2.	check how many users are there in the user system
 
![image](https://user-images.githubusercontent.com/42874340/110450184-edd25d80-80fd-11eb-8e2b-7a4840ae922d.png)

3.	go to administrator management and search by the user’s email
 
![image](https://user-images.githubusercontent.com/42874340/110450197-ef038a80-80fd-11eb-9b7f-5807fa5fedd1.png)

## Expected Result:
the searched user should be able to be modified by my manager account

## Severity: 
HIGH

**Comment by FangY2019** [comment]
The function of updating user information is for client users, while admin01 is an administrator.
