### ISSUE TITLE
something wrong with the hyperlink leading back to homepage

### ISSUE THREAD

**Issue by Wesley-Guoxy** [MacAquafina/reframery-frontend#148]
## Description:
I am browsing the item details page and find a hyperlink to directly go back to homepage. But the link direction seems not working.
## Environment:
Windows10, NodeJS14.16.0, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	open and browse a detailed item
2.	click on the “Back to marketplace” hyperlink
 
![image](https://user-images.githubusercontent.com/42874340/110458789-2296e280-8107-11eb-8076-4b807bbde792.png)

3.	you will be in such situation
 
![image](https://user-images.githubusercontent.com/42874340/110458798-2591d300-8107-11eb-888d-a8e2b31ea25a.png)

## Expected Result:
go back to the homepage when I use that hyperlink

## Severity: 
MIDDLE

**Comment by liangw27** [comment]
Duplicate issue with #29
