### ISSUE TITLE
issue with clicking on the "Back to marketplace" button 

### ISSUE THREAD

**Issue by behdadkha** [MacAquafina/reframery-frontend#29]
# Title
Issue with clicking on the "Back to marketplace" button.

# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
Click on any item under services and then "Back to marketplace", it says 

# Expected result
It should take the user back to the /canada/services page.
# Actual result
The page says "Resource not found at /home"

# Screenshot
![image](https://user-images.githubusercontent.com/24414469/109088916-4eb16d00-76de-11eb-8a92-345ec0ebf5f8.png)

# Severity
HIGH

**Comment by liangw27** [comment]
Solved and it will return to the homepage now. Thanks!
