### ISSUE TITLE
Clicking the Balance button on the cart page breaks the app

### ISSUE THREAD

**Issue by behdadkha** [MacAquafina/reframery-frontend#31]
# Title
Clicking the Balance button on the cart page breaks the app

# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
From the products page, click on the cart button, then click on Balance.

# Expected result
There shouldn't be a balance button in the first place.
The App could say, you are not logged in or please sign in to view your balance.

# Actual result
The App crashes and reveals the source code.

# Screenshot
![image](https://user-images.githubusercontent.com/24414469/109089470-4d347480-76df-11eb-8c33-e24706847c2e.png)

![image](https://user-images.githubusercontent.com/24414469/109089549-73f2ab00-76df-11eb-930f-839a2eb48359.png)

# Severity
HIGH

**Comment by liangw27** [comment]
I can click into the balance button on the cart pages to go to the balance page. It works.
