### ISSUE TITLE
/create-itme -> File upload doesn't work

### ISSUE THREAD

**Issue by behdadkha** [MacAquafina/reframery-frontend#32]
# Title
On the /create-item page, the file upload feature doesn't work

# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
Go to the /cart page and click on "Create Item". Fill out the form and upload an image.

# Expected result
The uploaded images should be displayed or it should say, one file uploaded.

# Actual result
The text "No File Selected" remains unchanged even after a successful upload.

# Screenshot
![image](https://user-images.githubusercontent.com/24414469/109090043-5d008880-76e0-11eb-8415-4d7cc9e62469.png)

# Severity
MEDIUM

**Comment by LIUK44** [comment]
It works now:)
