### ISSUE TITLE
Update user information page shows the error message under Email column

### ISSUE THREAD

**Issue by behdadkha** [MacAquafina/reframery-frontend#40]
# Title
The Update user information page shows the error message under Email column
# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
Login as the manager and go to Update user information, then enter "tester@gmail.com". And then click Search.

# Expected result
The second image is the expected behavior. 
# Actual result
The error message is displayed under the Email column.
# Screenshot
![image](https://user-images.githubusercontent.com/24414469/109097827-19148000-76ee-11eb-8a21-9ad810bb788a.png)

When another email is entered.

![image](https://user-images.githubusercontent.com/24414469/109097986-698bdd80-76ee-11eb-9fa8-1618af4a81a5.png)

# Severity
LOW

**Comment by FangY2019** [comment]
This is related to our design decision. An administrator only can search the user who has been validated. For a new registered user, the administrator should validate the user first in the Awaiting Validation section.
