### ISSUE TITLE
[Side Menu] Balance and Transactions menu buttons go to the same page

### ISSUE THREAD

**Issue by metes1** [MacAquafina/reframery-frontend#46]
*Balance* and *Transactions* buttons in the side menu go to the same page and display the exact same information.

**Severity:** Low

**Environment:**  
Device: ASUS Laptop  
OS: Windows 10  
Browser: Google Chrome

**Steps to Reproduce:**

1. Sign into account (I signed into user001@gmail.com)
2. Click My profile in the side menu.
3. Click the *Balance* button in the side menu. Next, click the *Transactions* button in the side menu.
4. Can see that these two buttons route to the same page.

**Expected Result:**  
Since they are two separate menu buttons, I expected them to do different things (go to a different page/display different info).

**Actual Result:**  
Both the *Balance* and *Transactions* buttons do the same thing and go to the same page.  

**Screenshot:**
<img width="947" alt="2" src="https://user-images.githubusercontent.com/35268717/109162252-fdd55f00-7745-11eb-91ec-978cad753aee.png">
This screenshot shows the result of clicking either the  *Balance* or *Transactions* button. Both pages route to the same URL:  http://localhost:3000/my-wallet

**Comment by liangw27** [comment]
solved and I kept only one item at the session of wallet.
