### ISSUE TITLE
[My Items] Edit button on item does not work

### ISSUE THREAD

**Issue by metes1** [MacAquafina/reframery-frontend#47]
On the Items page under *My Items*, the **Edit** buttons for the items do not work.

**Severity:** Medium

**Environment:**  
Device: ASUS Laptop  
OS: Windows 10  
Browser: Google Chrome

**Steps to Reproduce:**

1. Sign into client account (I signed into user001@gmail.com)
2. Click the **Items** button under *My Items* in the side menu.
3. Click the **Edit** button of an item (I clicked the Edit button for the Birthday Cake)

**Expected Result:**  
I would be brought to an edit page where I can edit the item.

**Actual Result:**  
Clicking the Edit button did nothing, I stayed on the same page. A '?' was added to the end of the URL.  

**Screenshot:**
<img width="928" alt="2" src="https://user-images.githubusercontent.com/35268717/109163933-db444580-7747-11eb-90f4-120e02337f84.png">

**Comment by LIUK44** [comment]
The button is renamed to remove and works now.
