### ISSUE TITLE
Can't see images on the product page

### ISSUE THREAD

**Issue by ipa-1** [MacAquafina/reframery-frontend#50]
**Description:** You can't see the market products on the product page when you enter the product page from the home page.

**Severity:** medium

**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact  

**Reproduction steps:** 
1. Click Canada.
2. You get to the product page, but you can't see the images of the products.

**Expected result:**
You should see the images for the products being described on the page.

**Actual result:**
You see the following:
![image](https://user-images.githubusercontent.com/28264369/109183975-7e06bf00-775c-11eb-920b-7b0069975698.png)

If you click on the product, the image does not show there either:
![image](https://user-images.githubusercontent.com/28264369/109183865-63344a80-775c-11eb-87bf-c32c46fe8cc3.png)

**Reproducibility Rate:** Consistent.

**Comment by FangY2019** [comment]
fixed in previous commit : https://github.com/MacAquafina/reframery-frontend/commit/ef61c50f12166e95e6cfa71dabae813b38613c86
