### ISSUE TITLE
[Item Details Page] Back to marketplace link redirects to a not found page

### ISSUE THREAD

**Issue by metes1** [MacAquafina/reframery-frontend#53]
The **Back to marketplace** link redirects to a blank page that says "Resource not found at /home". Can only leave this page by clicking the browser back button (since there are no other buttons on the page).

**Severity:** Medium  

**Environment:**  
Device: ASUS Laptop  
OS: Windows 10  
Browser: Google Chrome  

**Steps to Reproduce:**
1. From the starting page, click the Canada icon.  
2. Click the Signin button and sign into client account (user001@gmail.com).  
3. Click the **Cookies** item.  
4. Click the **Back to marketplace** link.  

**Expected Result:**  
After clicking **Back to marketplace**, user would be brought back to the page we were at before (home, which has multiple items listed).  

**Actual Result:**  
After clicking **Back to marketplace**,  user is redirected to a blank page that says "Resource not found at /home".

**Screenshots:**  
<img width="869" alt="2" src="https://user-images.githubusercontent.com/35268717/109186169-a68fb880-775e-11eb-9b51-5cfcead826e4.png">  
This screenshot shows the Item Details page and the **Back to marketplace** link.    

<img width="960" alt="2" src="https://user-images.githubusercontent.com/35268717/109186455-ee164480-775e-11eb-9068-568f479a4194.png">
This screenshot shows the page the user gets directed to after clicking the **Back to marketplace** link.

**Comment by liangw27** [comment]
Duplicate issue, you can check #29
