### ISSUE TITLE
When you click on items under "My Items", then a product, it goes to a blank page

### ISSUE THREAD

**Issue by ipa-1** [MacAquafina/reframery-frontend#56]
**Description:** When you go to the "My Items" page and click on a product, it directs you to a blank page.

**Severity:** medium

**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact  

**Reproduction steps:** 
User credentials:
username: user1111
password aaAA11
email: user1111@1111

1. Log in the Canada region
2. Under the "My items" tab
3. Click on the first item

**Expected result:**
You go to the product page.

**Actual result:**
You see the following screen:
![image](https://user-images.githubusercontent.com/28264369/109188667-29b20e00-7761-11eb-8a14-07bcd66b46d9.png)

**Reproducibility Rate:** Consistent

**Comment by LIUK44** [comment]
That was due to incomplete product design and now it was fixed:)
