### ISSUE TITLE
Entering the main page through the "Canada" option while logged in as admin or manager leads to an unexpected page

### ISSUE THREAD

**Issue by ipa-1** [MacAquafina/reframery-frontend#84]
**Description:** Entering the main page through the "Canada" option while logged in as admin or manager leads to an unexpected page

**Severity:** medium

**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact  

**Reproduction steps:** 
1. Log in as admin.
2. Go back to the home page (http://localhost:3000/).
3. Click Canada.

**Expected result:**
Invalid permissions error page, or invalid address error page

**Actual result:**
You reach a page where you dont have a cart, are able to see the products, and there is no nav bar, or regular admin options
![image](https://user-images.githubusercontent.com/28264369/109250988-a45a4800-77b8-11eb-9597-018c2992d6c8.png)

**Reproducibility Rate:** Consistent

**Comment by FangY2019** [comment]
From what our client expects, admin users can view the products but they can not purchase any product. That is why we allow admin user access product page. There might be a better way to implement it without making people confused.
