### ISSUE TITLE
[User Validation] A search for user by email returns empty for valid user emails

### ISSUE THREAD

**Issue by Warbler-tweet** [MacAquafina/reframery-frontend#86]
User credentials:
username: manager01
password: AAaa11
email: manager01@gmail.com

Severity: medium

Environment:
OS: Windows 10 
Browser: Google Chrome

Steps to reproduce:

1. navigate to Canada region
2. sign in as manager
3. select update user information
4. search for dudley@gmail.com, a registered user

Expected Behaviour:
  return a user associated with the email

Actual Behaviour:
  returns "incorrect email"
![usernotfound](https://user-images.githubusercontent.com/73412954/109335365-ed99ae80-782f-11eb-87db-52be979b8909.PNG)

**Comment by FangY2019** [comment]
Same to #40
