### ISSUE TITLE
[Profile] Entering a birthday using the keyboard yields unexpected date

### ISSUE THREAD

**Issue by bucklj4** [MacAquafina/reframery-frontend#94]
- Severity: Low

## Description
On the `My Profile`/`Account Setting` page, when entering a birthday using the keyboard, the number of digits in the year defaults to 6, yielding unexpected dates.

### Steps to Reproduce
1. Sign in as a manager (`manager01` credentials).
2. Enter the site through any country (for instance, `Canada`).
3. Click the `manager01` text in the top right of the header.
4. Click `Account Setting` in the left pane.
5. Select the `Birthday` textfield.
6. Enter using the keyboard the following string key-by-key: `2021-02-26`.

### Actual Result
The resulting birthday is shown as `202102-26-dd`.

### Expected Result
The resulting birthday is shown as `2021-02-26`.

### Attachments
<img width="1613" alt="Screenshot 2021-02-26 at 5 39 51 PM" src="https://user-images.githubusercontent.com/35265275/109362950-f2735800-7859-11eb-8595-56f2dd515d84.png">

**Comment by FangY2019** [comment]
It suggests to enter the numbers in the  order:  two digits for month, two digits for day, four digits for year. Otherwise, it will get an incorrect date.

![3](https://user-images.githubusercontent.com/54195303/111056475-0e2b5080-844d-11eb-95fc-74d7201e4767.PNG)
